name: symptomprefillapi
services:
  api:
    image: symptomprefillapi:latest-${NODE_ENV}
    build: .
    ports:
      - "3000:3000"

    # Loads environment variables from .env 
    env_file: .env

    # Ensure MongoDB starts before the API
    depends_on: [mongo]

    # #  Overrides the Dockerfile CMD, runs npm run dev to start the server
    # command: npm run dev

  mongo:
    image: mongo

    # Auto-restarts container on crash or Docker reboot
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local

